fullnameOverride: "llmaz"

backendRuntime:
  install: true

leaderWorkerSet:
  install: true
  namespace: llmaz-system

controllerManager:
  manager:
    args:
      - --health-probe-bind-address=:8081
      - --metrics-bind-address=127.0.0.1:8080
      - --leader-elect
      - --namespace=llmaz-system
  replicas: 1
